version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.1.0

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            src/com/craftinginterpreters/lox/.* run-build-service-1-job true
            src/com/craftinginterpreters/tool/.* run-build-service-2-job true
          base-revision: main
          config-path: .circleci/continue_config.yml
