version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Build"
          command: "echo build"
  test:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Test"
          command: "echo test"
  deploy:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Deploy"
          command: "echo deploys"

workflows:
  say-hello-workflow:
    jobs:
      - build
      - test
      - deploy:
          filters:
            branches:
              only: deploy
