version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Build"
          command: "echo build"
  test:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Test"
          command: "echo test"
  deploy:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Deploy"
          command: "echo deploys"

parameters:
  run-build-service-1-job:
    type: boolean
    default: false
  run-build-service-2-job:
    type: boolean
    default: false

workflows:
  service-1:
    when: << pipeline.parameters.run-build-service-1-job >>
    jobs:
      - build
      - test
  service-2:
    when: << pipeline.parameters.run-build-service-2-job >>
    jobs:
      - deploy